version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    environment:
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    volumes:
      - nextcloud:/var/www/html

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    volumes:
      - adminer_data:/var/lib/adminer

volumes:
  nextcloud:
  db_data:
  adminer_data:
